/**
 * sangaku
 * 産学連携のAPIです
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("BreweryApi", () => {
  let instance: api.BreweryApi
  beforeEach(function() {
    instance = new api.BreweryApi(config)
  });

  test("getBreweryDetail", () => {
    const id: any = undefined
    return expect(instance.getBreweryDetail(id, {})).resolves.toBe(null)
  })
  test("getBreweryList", () => {
    return expect(instance.getBreweryList({})).resolves.toBe(null)
  })
  test("searchBreweryList", () => {
    const keyword: any = undefined
    return expect(instance.searchBreweryList(keyword, {})).resolves.toBe(null)
  })
})

describe("SakeApi", () => {
  let instance: api.SakeApi
  beforeEach(function() {
    instance = new api.SakeApi(config)
  });

  test("getSakeDetail", () => {
    const sakeId: any = undefined
    return expect(instance.getSakeDetail(sakeId, {})).resolves.toBe(null)
  })
  test("getSakeList", () => {
    return expect(instance.getSakeList({})).resolves.toBe(null)
  })
  test("searchSakeList", () => {
    const keyword: any = undefined
    return expect(instance.searchSakeList(keyword, {})).resolves.toBe(null)
  })
})

