/* tslint:disable */
/* eslint-disable */
/**
 * sangaku
 * 産学連携のAPIです
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BreweryPlace
 */
export interface BreweryPlace {
    /**
     * 
     * @type {number}
     * @memberof BreweryPlace
     */
    bId: number;
    /**
     * 
     * @type {string}
     * @memberof BreweryPlace
     */
    bName: string;
    /**
     * 
     * @type {number}
     * @memberof BreweryPlace
     */
    pNumber: number;
    /**
     * 
     * @type {string}
     * @memberof BreweryPlace
     */
    bImgFilePath: string;
    /**
     * 
     * @type {string}
     * @memberof BreweryPlace
     */
    pCampName: string;
}

/**
 * Check if a given object implements the BreweryPlace interface.
 */
export function instanceOfBreweryPlace(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "bId" in value;
    isInstance = isInstance && "bName" in value;
    isInstance = isInstance && "pNumber" in value;
    isInstance = isInstance && "bImgFilePath" in value;
    isInstance = isInstance && "pCampName" in value;

    return isInstance;
}

export function BreweryPlaceFromJSON(json: any): BreweryPlace {
    return BreweryPlaceFromJSONTyped(json, false);
}

export function BreweryPlaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): BreweryPlace {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bId': json['B_id'],
        'bName': json['B_name'],
        'pNumber': json['P_number'],
        'bImgFilePath': json['B_imgFilePath'],
        'pCampName': json['P_campName'],
    };
}

export function BreweryPlaceToJSON(value?: BreweryPlace | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'B_id': value.bId,
        'B_name': value.bName,
        'P_number': value.pNumber,
        'B_imgFilePath': value.bImgFilePath,
        'P_campName': value.pCampName,
    };
}

