/* tslint:disable */
/* eslint-disable */
/**
 * sangaku
 * 産学連携のAPIです
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BreweryInfo } from './BreweryInfo';
import {
    BreweryInfoFromJSON,
    BreweryInfoFromJSONTyped,
    BreweryInfoToJSON,
} from './BreweryInfo';

/**
 * 
 * @export
 * @interface SakeDetail
 */
export interface SakeDetail {
    /**
     * 
     * @type {number}
     * @memberof SakeDetail
     */
    sKId: number;
    /**
     * 
     * @type {string}
     * @memberof SakeDetail
     */
    sKName: string;
    /**
     * 
     * @type {number}
     * @memberof SakeDetail
     */
    sKPrice: number;
    /**
     * 
     * @type {string}
     * @memberof SakeDetail
     */
    sKDescription: string;
    /**
     * 
     * @type {string}
     * @memberof SakeDetail
     */
    sKImgFilePath: string;
    /**
     * 
     * @type {BreweryInfo}
     * @memberof SakeDetail
     */
    breewry?: BreweryInfo;
}

/**
 * Check if a given object implements the SakeDetail interface.
 */
export function instanceOfSakeDetail(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sKId" in value;
    isInstance = isInstance && "sKName" in value;
    isInstance = isInstance && "sKPrice" in value;
    isInstance = isInstance && "sKDescription" in value;
    isInstance = isInstance && "sKImgFilePath" in value;

    return isInstance;
}

export function SakeDetailFromJSON(json: any): SakeDetail {
    return SakeDetailFromJSONTyped(json, false);
}

export function SakeDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): SakeDetail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sKId': json['SK_id'],
        'sKName': json['SK_name'],
        'sKPrice': json['SK_price'],
        'sKDescription': json['SK_description'],
        'sKImgFilePath': json['SK_img_file_path'],
        'breewry': !exists(json, 'breewry') ? undefined : BreweryInfoFromJSON(json['breewry']),
    };
}

export function SakeDetailToJSON(value?: SakeDetail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'SK_id': value.sKId,
        'SK_name': value.sKName,
        'SK_price': value.sKPrice,
        'SK_description': value.sKDescription,
        'SK_img_file_path': value.sKImgFilePath,
        'breewry': BreweryInfoToJSON(value.breewry),
    };
}

